// <auto-generated />
using System;
using GluetunWeb.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GluetunWeb.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719110858_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GluetunWeb.Api.Data.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ControlHostPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomVpnConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableHttpProxy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableSocks5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HttpProxyHostPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerCitiesOverride")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerCountriesOverride")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerHostnamesOverride")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Socks5ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Socks5HostPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomVpnConfigId");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("ProviderId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.CustomVpnConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawConfigEnc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VpnType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomVpnConfigs");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.GlobalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlServerApiKeyEnc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ControlServerAuth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlServerPasswordEnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlServerUser")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DockerHost")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GluetunImage")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HttpProxyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpProxyListeningAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HttpProxyLog")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpProxyPasswordEnc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HttpProxyStealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HttpProxyUser")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PortRangeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortRangeStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicIpApi")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicIpApiTokenEnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Socks5Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.PortAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("Port")
                        .IsUnique();

                    b.ToTable("PortAllocations");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenVpnPasswordEnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenVpnUserEnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerCities")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerCountries")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerHostnames")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerRegions")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VpnType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WireGuardAddresses")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WireGuardPresharedKeyEnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WireGuardPrivateKeyEnc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.Connection", b =>
                {
                    b.HasOne("GluetunWeb.Api.Data.CustomVpnConfig", "CustomVpnConfig")
                        .WithMany()
                        .HasForeignKey("CustomVpnConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GluetunWeb.Api.Data.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomVpnConfig");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.PortAllocation", b =>
                {
                    b.HasOne("GluetunWeb.Api.Data.Connection", "Connection")
                        .WithMany("PortAllocations")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("GluetunWeb.Api.Data.Connection", b =>
                {
                    b.Navigation("PortAllocations");
                });
#pragma warning restore 612, 618
        }
    }
}
